---
title: "SDPP-ABCD-TabDat User Manual"
author: "Kunru Song"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 4
---

# Citation

If you would like to use any codes from this SDPP, please kindly cite our published article (below is a APA-format Citation):

>    Song K, Zhang JL, Zhou N, Fu Y, Zou B, Xu LX, Wang Z, Li X, Zhao Y,Potenza M, Fang X, Zhang JT. Youth Screen Media Activity Patterns and Associations With Behavioral Developmental Measures and Resting-state Brain Functional Connectivity. J Am Acad Child Adolesc Psychiatry.2023 Mar 20:S0890-8567(23)00132-6.doi: 10.1016/j.jaac.2023.02.014.Epub ahead of print. PMID: 36963562.
    
# Common Usage Notes

  1. Please set all necessary parameters in SDPP_ParaSet.R before running any codes in this pipeline and then source it.
  
  2. Coding Scheme for ABCD Demographic variable data could be found in Step 1 and Step 2, as well as ABCD-DAIRC github repository:[analysis-NDA](https://github.com/ABCD-STUDY/analysis-nda). A coding scheme table was also provided by this pipeline.
  
## Abbreviation Table

Converted from ./.github/SDPP_AbbrTable.xlsx by [Table Convert Online](https://tableconvert.com/)

| Common |                                | Novel Technology |                                                |
|--------|--------------------------------|------------------|------------------------------------------------|
| T0     | Baseline Wave Data             | SMA              | Screen Media Activity                          |
| T1     | One-year follow-up             | OS               | OwnerShip                                      |
| T2     | Two-year follow-up             | STQ              | Screen Time Questionnaire                      |
| T3     | Three-year follow-up           | TPD              | TyPical Day (prefix) or Time Per Day (postfix) |
| T4     | Four-year follow-up            | TPW              | Time Per Week                                  |
| MVA    | Missing Value Analysis         | open             | calculated value from open-answered STQ items  |
| MI     | Multiple Imputation            | weekday          | in a typical weekday                           |
| Rep    | Auto-generated Report          | weekend          | in a typical weekend day                       |
| Rec    | Re-coded data                  | School           | School-related work                            |
| Raw    | Raw data                       | SMQ              | Social Media Questionnaire                     |
| Imp    | Imputed data                   | SOC              | SOCial media apps                              |
| Reorg  | Re-organized data              | SMAS             | bergen Social Media Addiction Scale            |
| Comp   | Compare                        | MVOC             | Multiplayer Videogame Online Chatting          |
| ALL    | all avaiable waves in ABCD 5.0 | UM               | Use Most                                       |
|        |                                | NOFE             | the Number Of FollowErs                        |
|        |                                | NOFI             | the Number Of FollowIngs                       |
|        |                                | NOA              | the Number Of Account                          |
|        |                                | MP               | Mobile Phone                                   |
|        |                                | MPIQ             | Mobile Phone Involvement Questionnaire         |
|        |                                | VGAS             | Video Game Addiction Scale                     |
|        |                                | ODQ              | Online Dating Questionnaire                    |
|        |                                | SUAB             | Screen Usage Around Bedtime                    |


## Coding Scheme Table

| Variable Names                               | Descriptions                                                          | Variable Type | Categories            | Coding Scheme                                                           |
|----------------------------------------------|-----------------------------------------------------------------------|---------------|-----------------------|-------------------------------------------------------------------------|
| SexAssigned                                  | Youth's Sex assigned at birth                                         |               |                       |                                                                         |
| VisitType                                    |                                                                       |               |                       |                                                                         |
| Education_13L                                | Parent-reported Youth's Education Level                               |               | 1, 2, 3, 4, 5         | "from 1 (1st or 2nd                                                     |
| grade or lower) to 5 (6th grade or greater)" |
| SiteID                                       |                                                                       |               |                       |                                                                         |
| FamilyID                                     |                                                                       |               |                       |                                                                         |
| GroupID                                      |                                                                       |               |                       |                                                                         |
| SchoolID                                     |                                                                       |               |                       |                                                                         |
| DistrictID                                   |                                                                       |               |                       |                                                                         |
| ACS_Weight                                   |                                                                       |               |                       |                                                                         |
| Race_6L                                      | Parent-identified Youth's Race                                        |               | "White; Black;        |
| Asian; Mixed/Other"                          | reference: White                                                      |
| Ethnicity_PrntRep                            | Parent-identified Youth's Ethnicity                                   |               | "Hispanic; non-       |
| Hispanic"                                    | reference: Hispanic                                                   |
| Handedness                                   | Youth's Handedness                                                    |               | right; mixed; left    | reference: right                                                        |
| ParentsMarital_2L                            | Parent-reported Marital Status                                        |               | "Married or living    |
| with partner; Single"                        | "reference: Married or                                                |
| living with partner"                         |
| ParentsHighEdu_2L                            | Parent-reported the Highest Education Level                           |               | "high school or less; |
| college education"                           | "reference: high school                                               |
| or less"                                     |
| ParentsMarital_X_Employ                      | the Interaction Term of Parent-reported Marital and Employment Status |               | "married 0/1/2 in     |
| LF(labor force); other 0/1 in LF"            | this variable is not entered to LME model                             |
| Relationship_3L                              | Parent-reported Family Structure                                      |               | "single; sibling;     |
| twin/triplet;"                               | reference: single                                                     |
| HouseholdSize                                | Parent-reported the number of family member in household              |               | 1, 2, 3, 4, 5         | "from 1 (2 to 3 or less people in household) to 5 (7 people and more in |
| household)"                                  |
| "Household                                   |
| Structure"                                   | Parent-reported household structure                                   |               | "another household;   |
| single household"                            | "reference: another                                                   |
| household"                                   |
| BirthCountry                                 |                                                                       |               | other country; USA    | "reference: other                                                       |
| country"                                     |
| FamilyIncome                                 |                                                                       |               | 1, 2, 3, 4, 5, 6      | "from 1 (Less than                                                      |
| $5,000) to 6 ($200,000                       |
| and greater)"                                |



# Data Usage Notes

## Missing Value Imputation

  1. In Step 3, missing values (NAs) in some key demographic variable will be processed by R package mice, which reads as follows: _src_subject_id_, _interview_age_, _SexAssigned_, _BMI_, _BirthCountry_, _YouthNativeLang_, _Religon_2L_, _Race_PrntRep_, _Ethnicity_PrntRep_, _ParentsHighEdu_5L_, _ParentsMarital_6L_, _ParentEmploy_, _FamilyIncome_, _HouseholdStructure_, _HouseholdSize_, _Relationship_3L_. Variables with missing values would be imputed using chained equations model. The final imputed dataset will be generated by combining all imputed dataset. The number of imputed datasets could be changed in SDPP_ParaSet (default is 100 with 25 iterations). At the same time, a mice.mids object will also be saved into a RDS file in your SDPP project folder (at /"Project"/Res_2_Results/Res_Preproc/, "Project" is the folder name that you set as a SDPP Project Directory). A more practical way to use multiple-imputed data is calling funcitons in mice package (i.e. with and pool) to build your statistical models on each imputed dataset and then poolling their estimates together. This is a more conventional method when using multiple imputation to handle missing values. In addition, you can change these 'Key Demographic Variables' processed by multiple imputation in **DataPreproc_Step3_DemographicImpute.R** (Code Chunk 6, Line 122 - 130)
  
  2. In Step 5, missing values (NAs) in youth-reported screen use time, MPIQ, SMAS, VGAS, SUAB will be processed by KNN imputation, which is implemented by a MATLAB offical function _knnimpute_ (requires MATLAB offical toolbox: _Bioinformatics Toolbox_). In detail, the Step 5 script will use R.matlab package to create a local MATLAB server and then call the MATLAB function in R environment. Please make sure you have correctly installed the required R package and relevant MATLAB version.

# Data Coding Notes
  
## Demographic Variables
  
  1. Coding scheme for ABCD demographic variable are referred to the ABCD-DAIRC codes. [Find here](https://github.com/ABCD-STUDY/analysis-nda).
  2. A detailed coding scheme table cound be found in /.github/SDPP_CodingScheme.xlsx, which follows the format of **Table S2** in the supplemental materials of our published JAACAP article.[Article Link](https://www.sciencedirect.com/science/article/pii/S0890856723001326)

## ABCD Screen Time Questionnaire

### Changes in ABCD 5.0

  1. In Step 4, some coding details should be noted as follows (Bagot et al., 2022, Dev Cog Neurosci):
  
  - 1.1 Item Choice Changed
    - Beginning in Year 2, the activities listed were changed slightly to reflect the increase in video streaming: watching TV shows or movies changed to “watching or streaming TV shows or movies”; watching videos (such as YouTube) changed to “watching or streaming videos or live streaming (such as YouTube, Twitch)"
  - 1.2 New Items Added
    - Time spent playing videogames was broken down into “time spent on single player”and “multiplayer gaming”. 
    - Editing photos or videos to post on social media was added;
    - “searching or browsing the internet that is not "for school” was added.
    - Total time spent on all non-school related screen usage activities was added.
    - Importantly, the response format in Year 2 was changed from categories to open format, where individuals input the hours and minutes, they estimated spending on each screen usage activity. 
  - 1.3 Coding Method Changed 
    - Bagot et al. have reported their harmonizing method to capture such changes beginning in two-year follow-up wave (Page 5, Section 2.2.10 Self-reported screen usage). SDPP-ABCD-TabDat, here, followed the work done by Bagot et al.
    
        >   "To harmonize screen usage data across Baseline, Year 1, and Year 2 for analyses here, it was necessary to transform Year 2 open responses to categories consistent with Baseline and Year 1. This was done by summing hours and minutes for each activity in Year 2 and recoding it to the categories (with anything above 4 h recoded as ‘4 + hours’), according to a 6-point scale: 0 h, < 1 h, 1–2 h, 2–3 h, 3–4 h, and > 4 h. For analyses, these were coded as 0–5, respectively. Furthermore, ‘editing photos and videos’ and ‘searching or browsing the internet’ were omitted as these items were not queried at previous assessments. Time spent on single player and multiplayer gaming was collapsed into a single category of “video games” (by summing them) to be consistent with previous assessments.".
      
    - In SDPP-ABCD-TabDat, however, Step 4 will do a slightly different coding for screen use time, where a 7-level ordinal coding will be applied to 12 items in the ABCD STQ. This was done by the following formula: Screen Use Time = hours + minutes/60. The calculated time from open-answered items will be re-coding into 0, 0.25, 0.5, 1, 2, 3, 4. The unit is hours. Such re-coding could preserve the raw scale of time from these items, which is beneficial to do clustering analysis. According to the description in previous close-answered items in STQ, which reads as "1½ hours would be coded as 1 hour, rather than 2 hours", Step 4 will collapse 0.75, 1, 1.25 and 1.5 into 1 hour; 1.75, 2, 2.25, 2.5 into 2 hours; 2.75, 3, 3.25, 3.5 into 3 hours; 3.75, 4 and above into 4+ hours.
    
    
    >    _Bagot KS, Tomko RL, Marshall AT, Hermann J, Cummins K, Ksinan A, Kakalis M, Breslin F, Lisdahl KM, Mason M, Redhead JN, Squeglia LM, Thompson WK, Wade T, Tapert SF, Fuemmeler BF, Baker FC. Youth screen use in the ABCD® study. Dev Cogn Neurosci. 2022 Sep 1;57:101150. doi: 10.1016/j.dcn.2022.101150. Epub ahead of print. PMID: 36084446; PMCID: PMC9465320._

### MPIQ

  - Mobile Phone-related Items in the ABCD STQ
    
    -  Mobile phone involvement questionnaire (MPIQ). MPIQ is an 8-item questionnaire designed to assess problematic mobile phone usage, beginning in Year 2. Reference article could be found at:
        
    >     Needing to connect: The effect of self and others on young people's involvement with their mobile phones (2010).
        
    -  MPIQ Item Descriptions: How much do you agree with the following statements in relation to your cell phone use?
    -  Coding: 1=Strongly Disagree; 2=Disagree; 3=Somewhat Disagree; 4=Neither Agree nor Disagree;5=Somewhat Agree; 6=Agree; 7=Strongly Agree; 777=Refuse to Answer.MPIQ Items Descriptions (Q1-Q8): 
    -  screentime_phone1: I interrupt whatever else I am doing when I am contacted on my phone;
    -  screentime_phone2: I often use my phone for no particular reason; 
    -  screentime_phone3: I feel connected to others when I am using my phone; 
    -  screentime_phone4: Arguments have arisen with others because of my phone use; 
    -  screentime_phone5: I lose track of how much I am using my phone; 
    -  screentime_phone6: I often think about my phone when I am not using it; 
    -  screentime_phone7: I have been unable to reduce my phone use; 
    -  screentime_phone8: The thought of being without my phone makes me feel distressed

### SMAS and VGAS

  - 2.5 SMAS and VGAS
    -  Social Media Addiation Scale (SMAS, 6 Items) 
        -  Coding: 1=Never; 2=Very rarely; 3=Rarely; 4=Sometimes; 5=Often; 6=Very often; 777=Refuse to answer
        -  screentime_smqa1: I spend a lot of time thinking about social media apps or planning my use of social media apps;
        -  screentime_smqa2: I feel the need to use social media apps more and more; 
        -  screentime_smqa3: I use social media apps so I can forget about my problems; 
        -  screentime_smqa4: I've tried to use my social media apps less but I can't; 
        -  screentime_smqa5: I've become stressed or upset if I am not allowed to use my social media apps; 
        -  screentime_smqa6: I use social media apps so much that it has had a bad effect on my schoolwork or job; 
    -  Video Game Addiction Scale (VGAS)
        - Items are same with SMAS but replace the "social media" with "playing video games".
        - screentime_vgaq1 ~ screentime_vgaq6	

### SUAB

  - Screen Usage Around Bedtime (SUAB)
    -  A 9-item measure was administered to youth to assess engagement in activities, including screen time activities, prior to sleeping. Items were modified from Lemola et al. (2015) and Arora et al. (2014). On a 5-point Likert scale ranging from 1 (never) to 5 (every night), youth reported how often (in the past week) they engaged in the following activities while already in bed before going to sleep: watch TV or movies, play video games, play music, talk on the phone or text, spend time online on social media, browse the internet, use a computer/laptop for studying. sq3-sq13 shared the same answer items.
    - Coding: 1=0 nights in the past week; 2=1-2 nights; 3=3-4 nights; 4=5-7 nights; 777=Refused to answer.
        - screentime_sq3: Watch or stream movies, videos, or TV shows
        - screentime_sq4: Play video games
        - screentime_sq5: Play music
        - screentime_sq6: Talk on the phone or text (If you do not own a phone, choose 0 nights)
        - screentime_sq7: Spend time online on social media (e.g. Facebook)
        - screentime_sq8: Spend time in chat rooms
        - screentime_sq9: Browse the Internet, Google-ing (not school related)
        - screentime_sq10: Use a computer/laptop for studying
        - screentime_sq11: Reading
    - Four additional items were asked related to sleep and media use which were adapted from questions in a National Sleep Foundation poll (Gradisar et al., 2013). 
        - screentime_sq1: Is there a TV set or an Internet connected electronic device (computer, iPad, phone) in your bedroom? 1=Yes; 0=No; 777=Refuse to answer	
        - screentime_sq2: What do you usually do with your phone when you are ready to go to sleep? Do you: -1=Not Applicable ; 1=Turn the phone off ; 2=Put the ringer on silent or vibrate ; 3=Leave the ringer on ; 4=Put it outside of the room where I sleep ; 777=Refuse to answer
        - screentime_sq12: In the past week, how often have you had phone calls, text messages or emails that wake you after trying to go to sleep? 1=0 nights in the past week; 2=1-2 nights; 3=3-4 nights; 4=5-7 nights; 777=Refused to answer
        - screentime_sq13: In the past week, when you woke up during the night,  how often have you used your phone or other device to send messages/play games/search or browse the internet/use social media/read or write emails? 1=0 nights in the past week; 2=1-2 nights; 3=3-4 nights; 4=5-7 nights; 777=Refused to answer
