---
title: "Standard Data Preprocessing Pipeline for ABCD Tabulated Data"
subtitle: "SDPP-ABCD-TabDat"
author: "Kunru Song"
date: "`r Sys.Date()`"
output: rmarkdown::github_document
---
### Basic Infomation

**Data Version:** ABCD 5.0 Data Release (tabulated data)

**Author Info:** Kunru Song, PhD Student at BNU, supervised by Dr.Jin-tao Zhang.

[Kunru's Personal Profile (Researchgate)](https://www.researchgate.net/profile/Kunru-Song)

[Dr. Jin-tao Zhang's Lab (Researchgate)](https://www.researchgate.net/lab/Jintao-Zhang-Lab-2)

**First Created Date:** 2022.06

-----

### Citation and Suggestions

1.  If you would like to use any codes from this SDPP, please kindly cite our published article (below is a APA-format Citation):

    >    _Song K, Zhang JL, Zhou N, Fu Y, Zou B, Xu LX, Wang Z, Li X, Zhao Y,Potenza M, Fang X, Zhang JT. Youth Screen Media Activity Patterns and Associations With Behavioral Developmental Measures and Resting-state Brain Functional Connectivity. J Am Acad Child Adolesc Psychiatry.2023 Mar 20:S0890-8567(23)00132-6.doi: 10.1016/j.jaac.2023.02.014.Epub ahead of print. PMID: 36963562._

2.  **SDPP-ABCD-TabDat** now is only available for Dr. Jin-tao Zhang's Team, which is not allowed to be shared.

3. Any bugs found in this pipeline should be reported in Github Issues. 

4. Abbreviation Table

Converted from ./.github/SDPP_AbbrTable.xlsx by [Table Convert Online](https://tableconvert.com/)

| Common |                        | Novel Technology |                                                |
|--------|------------------------|------------------|------------------------------------------------|
| T0     | Baseline Wave Data     | SMA              | Screen Media Activity                          |
| T1     | One-year follow-up     | OS               | OwnerShip                                      |
| T2     | Two-year follow-up     | STQ              | Screen Time Questionnaire                      |
| T3     | Three-year follow-up   | TPD              | TyPical Day (prefix) or Time Per Day (postfix) |
| T4     | Four-year follow-up    | TPW              | Time Per Week                                  |
| MVA    | Missing Value Analysis | open             | calculated value from open-answered STQ items  |
| MI     | Multiple Imputation    | weekday          | in a typical weekday                           |
| Rep    | Auto-generated Report  | weekend          | in a typical weekend day                       |
| Rec    | Re-coded data          | School           | School-related work                            |
| Raw    | Raw data               | SMQ              | Social Media Questionnaire                     |
| Imp    | Imputed data           | SOC              | SOCial media apps                              |
|        |                        | SMAS             | bergen Social Media Addiction Scale            |
|        |                        | MVOC             | Multiplayer Videogame Online Chatting          |
|        |                        | UM               | Use Most                                       |
|        |                        | NOFE             | the Number Of FollowErs                        |
|        |                        | NOFI             | the Number Of FollowIngs                       |
|        |                        | NOA              | the Number Of Account                          |
|        |                        | MP               | Mobile Phone                                   |
|        |                        | MPIQ             | Mobile Phone Involvement Questionnaire         |
|        |                        | VGAS             | Video Game Addiction Scale                     |
|        |                        | ODQ              | Online Dating Questionnaire                    |
|        |                        | SUAB             | Screen Usage Around Bedtime                    |

-----

### User Mannual

#### Update Logs

 - 2023.07.07
   - Completed Step 4 and write Usage Notes in README, which provide a comprehensive overview for using SDPP-ABCD-TabDat.
   - Update some codes to generate more elegant code running logs, which would be saved into _'Res_1_Logs'_ folders under your project directory. SDPP_ParaSet will generate a log with postfix 0. The numeric postfix is correspond to the step number.

 - 2023.07.06
   - Modifed Step 4 for ABCD V5.0. Added a new section in README to illstruate some details in Step 4.
   - Screen Use Time now will be re-coded into 7-level oridinal variable, data type is numeric.

 - 2023.07.05
   - Modifed Step 3 for ABCD V5.0.
   - Created a new script _'SDPP_ParaSet.R'_, which is the _all in one_ parameters setting script for SDPP-ABCD-TabDat. _'SDPP_ParaSet.R'_ should be executed before any steps of SDPP-ABCD-TabDat to source all common parameters and libary all common packages. Log for _'SDPP_ParaSet.R'_ will be save into Log_SDPP-ABCD-TabDat_0.txt
   
 - 2023.07.03
 
   - Errors in measures of height and weight that noted in _'ABCD 5.0 Changes and Known Issues'_ (Page 9) were processed in Step 1 R script. please see attached file _'ABCD5.0_BMI_NotesTable.xlsx'_, where Sheet 'NotesTable' was directly copied from _'ABCD 5.0 Changes and Known Issues.doc'_ (Page 9 & 10), sheet 'ManualCorrectiveTable' was manually generated by Kunru Song (2023.07.03) to correct the value with each subject in it. The second sheet could be used to replace ('correct') the measured values in /physical-health/ph_y_anthro.csv (that is what Step 1 would do). Please download and place it within the folder where SDPP-ABCD-TabDat scripts were storage.
   - At 4-year follow-up, the EHIS was measured again. To keep consistent, youth's handedness indicated by EHIS was determined by the baseline measure, which would be seen as a time-invariant variable.(Section 8 in Step 1)
   - Add function to automatedly save logs.
   - Merge Intersex-Male and Male into Male. Because the number of intersex-male subjects is too small.
   
 - 2023.07.01

   - Add some codes to re-code rel_group_id into a new numeric variable, which could describe the order of youths from same family. A new variable named GroupID will be created within execution of Step1, range from 0 to 3. For single-child family, the value would be set to 0. For multi-child family (sibling, twin or triplet), the corresponding value indicates the order of youths in their family.
   - Old Variables with prefix _'GeneInfo'_ now were replaced by _'GI'_.
   - The top five Principal component of genetic ancestry would be preserved in the preprocess data frame. I did this as a conventional choice such as aCompcor and tCompcor, where we usually extract the top five principal components. It should be noted that such conventional choice did not have particular reason. Usually, the top five PCs are enough to capture the variations in raw data. Because I did not find proper justification for ABCD gentic ancestry PCs, such choice may be an optional and practical process for the genetic ancestry data. Any comments are welcome to address this issue.
 
 - 2023.06.29
   
   - Revising all codes for ABCD V5.0 Tabulated Data (NDA Collection ID: 2147)
    - In ABCD 5.0 tabulated data, _'src_subject_id'_ would be used as participant identifier.
   - [ABCD 5.0 Tabulated Release Data](https://nda.nih.gov/study.html?id=2147)
   - [ABCD 5.0 Data Dictionary](https://data-dict.abcdstudy.org/)
   - [ABCD 5.0 Release Notes & Update Logs](https://wiki.abcdstudy.org/release-notes/start-page.html)

 - 2023.06.06
  
   - To improve compatability of CSV files across different environment (R, Python, MATLAB, LibreOffice, Excel), vaiable names (i.e., Column Names) have been modified. All '.' were replaced by '_'.

 - 2023.06.05
   
   - Add additional parameter in write.csv with fileEncoding='UTF-8'. Now all CSV-files generated by SDPP-ABCD-TabDat will be formated in UTF-8 encoding type.
   
 - 2023.06.03

   - To keep consistent with NDA platform, the variable _'subjectkey'_ will be used as Subject ID to merge data. Because _'subjectkey'_ is the _'NDAR Global Unique Identifier (GUID) for research subject'_. Anyone using ABCD data could easily apply GUID filter to create their own NDA Study, which is the requirements of ABCD DUC terms and condition.
   - Added more comments into R script. Added code blocks to make everything easy to read.
   
-----

####  Usage Notes

  1. Please set all necessary parameters in SDPP_ParaSet.R before running any codes in this pipeline and then source it.
  
  2. Coding Scheme for ABCD Demographic variable data could be found in Step 1 and Step 2, as well as ABCD-DAIRC github repository:[analysis-NDA](https://github.com/ABCD-STUDY/analysis-nda).
  
  3. In Step 3, some key demographic variable will be processed through R package mice, which reads as follows: _src_subject_id_, _interview_age_, _SexAssigned_, _BMI_, _BirthCountry_, _YouthNativeLang_, _Religon_2L_, _Race_PrntRep_, _Ethnicity_PrntRep_, _ParentsHighEdu_5L_, _ParentsMarital_6L_, _ParentEmploy_, _FamilyIncome_, _HouseholdStructure_, _HouseholdSize_, _Relationship_3L_. Variables with missing values would be imputed using chained equations model. The final imputed dataset will be generated by combining all imputed dataset. The number of imputed datasets could be change in SDPP_ParaSet (default is 50). At the same time, a mice.mids object will also be saved into a RDS file in your SDPP project folder. A more practical way to use the multiple-imputed data is calling funcitons in mice package (i.e. with and pool) to build your statistical models on each imputed dataset and then poolling their estimates together. This is a more conventional method when using multiple imputation to handle missing values. In addition, you can change these 'Key Demographic Variables' processed by multiple imputation in **DataPreproc_Step3_DemographicImpute.R** (Code Chunk 6, Line 122 - 130)
  
  4. In Step 4, some coding details should be noted as follows (Bagot et al., 2022, Dev Cog Neurosci):
  
  - 4.1 Item Choice Changed
    - Beginning in Year 2, the activities listed were changed slightly to reflect the increase in video streaming: watching TV shows or movies changed to “watching or streaming TV shows or movies”; watching videos (such as YouTube) changed to “watching or streaming videos or live streaming (such as YouTube, Twitch)"
  - 4.2 New Items Added
    - 4.2.1 Time spent playing videogames was broken down into “time spent on single player”and “multiplayer gaming”. 
    - 4.2.2 Editing photos or videos to post on social media was added;
    - 4.2.3 “searching or browsing the internet that is not "for school” was added.
    - 4.2.4 Total time spent on all non-school related screen usage activities was added.
    - 4.2.5 Importantly, the response format in Year 2 was changed from categories to open format, where individuals input the hours and minutes, they estimated spending on each screen usage activity. 
  - 4.3 Coding Method Changed 
    - Bagot et al. have reported their harmonizing method to capture such changes beginning in two-year follow-up wave (Page 5, Section 2.2.10 Self-reported screen usage). SDPP-ABCD-TabDat, here, followed the work done by Bagot et al.
    
        >   "To harmonize screen usage data across Baseline, Year 1, and Year 2 for analyses here, it was necessary to transform Year 2 open responses to categories consistent with Baseline and Year 1. This was done by summing hours and minutes for each activity in Year 2 and recoding it to the categories (with anything above 4 h recoded as ‘4 + hours’), according to a 6-point scale: 0 h, < 1 h, 1–2 h, 2–3 h, 3–4 h, and > 4 h. For analyses, these were coded as 0–5, respectively. Furthermore, ‘editing photos and videos’ and ‘searching or browsing the internet’ were omitted as these items were not queried at previous assessments. Time spent on single player and multiplayer gaming was collapsed into a single category of “video games” (by summing them) to be consistent with previous assessments.".
      
    - In SDPP-ABCD-TabDat, however, Step 4 will do a slightly different coding for screen use time, where a 7-level ordinal coding will be applied to 12 items in the ABCD STQ. This was done by the following formula: Screen Use Time = hours + minutes/60. The calculated time from open-answered items will be re-coding into 0, 0.25, 0.5, 1, 2, 3, 4. The unit is hours. Such re-coding could preserve the raw scale of time from these items, which is beneficial to do clustering analysis. According to the description in previous close-answered items in STQ, which reads as "1½ hours would be coded as 1 hour, rather than 2 hours", Step 4 will collapse 0.75, 1, 1.25 and 1.5 into 1 hour; 1.75, 2, 2.25, 2.5 into 2 hours; 2.75, 3, 3.25, 3.5 into 3 hours; 3.75, 4 and above into 4+ hours.
    
    
    >    _Bagot KS, Tomko RL, Marshall AT, Hermann J, Cummins K, Ksinan A, Kakalis M, Breslin F, Lisdahl KM, Mason M, Redhead JN, Squeglia LM, Thompson WK, Wade T, Tapert SF, Fuemmeler BF, Baker FC. Youth screen use in the ABCD® study. Dev Cogn Neurosci. 2022 Sep 1;57:101150. doi: 10.1016/j.dcn.2022.101150. Epub ahead of print. PMID: 36084446; PMCID: PMC9465320._

  - 4.4 Mobile Phone-related Items in the ABCD STQ
    
    -  Mobile phone involvement questionnaire (MPIQ). MPIQ is an 8-item questionnaire designed to assess problematic mobile phone usage, beginning in Year 2. Reference article could be found at:
        
    >     Needing to connect: The effect of self and others on young people's involvement with their mobile phones (2010).
        
    -  MPIQ Item Descriptions: How much do you agree with the following statements in relation to your cell phone use?
    -  Coding: 1=Strongly Disagree; 2=Disagree; 3=Somewhat Disagree; 4=Neither Agree nor Disagree;5=Somewhat Agree; 6=Agree; 7=Strongly Agree; 777=Refuse to Answer.MPIQ Items Descriptions (Q1-Q8): 
    -  screentime_phone1: I interrupt whatever else I am doing when I am contacted on my phone;
    -  screentime_phone2: I often use my phone for no particular reason; 
    -  screentime_phone3: I feel connected to others when I am using my phone; 
    -  screentime_phone4: Arguments have arisen with others because of my phone use; 
    -  screentime_phone5: I lose track of how much I am using my phone; 
    -  screentime_phone6: I often think about my phone when I am not using it; 
    -  screentime_phone7: I have been unable to reduce my phone use; 
    -  screentime_phone8: The thought of being without my phone makes me feel distressed
    
  - 4.5 SMAS and VGAS
    -  Social Media Addiation Scale (SMAS, 6 Items) 
        -  Coding: 1=Never; 2=Very rarely; 3=Rarely; 4=Sometimes; 5=Often; 6=Very often; 777=Refuse to answer
        -  screentime_smqa1: I spend a lot of time thinking about social media apps or planning my use of social media apps;
        -  screentime_smqa2: I feel the need to use social media apps more and more; 
        -  screentime_smqa3: I use social media apps so I can forget about my problems; 
        -  screentime_smqa4: I've tried to use my social media apps less but I can't; 
        -  screentime_smqa5: I've become stressed or upset if I am not allowed to use my social media apps; 
        -  screentime_smqa6: I use social media apps so much that it has had a bad effect on my schoolwork or job; 
    -  Video Game Addiction Scale (VGAS)
        - Items are same with SMAS but replace the "social media" with "playing video games".
        - screentime_vgaq1 ~ screentime_vgaq6	
  
  - 4.6 Screen Usage Around Bedtime (SUAB)
    -  A 9-item measure was administered to youth to assess engagement in activities, including screen time activities, prior to sleeping. Items were modified from Lemola et al. (2015) and Arora et al. (2014). On a 5-point Likert scale ranging from 1 (never) to 5 (every night), youth reported how often (in the past week) they engaged in the following activities while already in bed before going to sleep: watch TV or movies, play video games, play music, talk on the phone or text, spend time online on social media, browse the internet, use a computer/laptop for studying. sq3-sq13 shared the same answer items.
    - Coding: 1=0 nights in the past week; 2=1-2 nights; 3=3-4 nights; 4=5-7 nights; 777=Refused to answer.
        - screentime_sq3: Watch or stream movies, videos, or TV shows
        - screentime_sq4: Play video games
        - screentime_sq5: Play music
        - screentime_sq6: Talk on the phone or text (If you do not own a phone, choose 0 nights)
        - screentime_sq7: Spend time online on social media (e.g. Facebook)
        - screentime_sq8: Spend time in chat rooms
        - screentime_sq9: Browse the Internet, Google-ing (not school related)
        - screentime_sq10: Use a computer/laptop for studying
        - screentime_sq11: Reading
    - Four additional items were asked related to sleep and media use which were adapted from questions in a National Sleep Foundation poll (Gradisar et al., 2013). 
        - screentime_sq1: Is there a TV set or an Internet connected electronic device (computer, iPad, phone) in your bedroom? 1=Yes; 0=No; 777=Refuse to answer	
        - screentime_sq2: What do you usually do with your phone when you are ready to go to sleep? Do you: -1=Not Applicable ; 1=Turn the phone off ; 2=Put the ringer on silent or vibrate ; 3=Leave the ringer on ; 4=Put it outside of the room where I sleep ; 777=Refuse to answer
        - screentime_sq12: In the past week, how often have you had phone calls, text messages or emails that wake you after trying to go to sleep? 1=0 nights in the past week; 2=1-2 nights; 3=3-4 nights; 4=5-7 nights; 777=Refused to answer
        - screentime_sq13: In the past week, when you woke up during the night,  how often have you used your phone or other device to send messages/play games/search or browse the internet/use social media/read or write emails? 1=0 nights in the past week; 2=1-2 nights; 3=3-4 nights; 4=5-7 nights; 777=Refused to answer
