---
title: "SDPP-ABCD-TabDat User Manual"
author: "Kunru Song"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 4
---

# Citation

If you would like to use any codes from this SDPP, please kindly cite our published article (below is a APA-format Citation):

>    Song K, Zhang JL, Zhou N, Fu Y, Zou B, Xu LX, Wang Z, Li X, Zhao Y,Potenza M, Fang X, Zhang JT. Youth Screen Media Activity Patterns and Associations With Behavioral Developmental Measures and Resting-state Brain Functional Connectivity. J Am Acad Child Adolesc Psychiatry.2023 Mar 20:S0890-8567(23)00132-6.doi: 10.1016/j.jaac.2023.02.014.Epub ahead of print. PMID: 36963562.
    
# Common Usage Notes

  1. Please set all necessary parameters in SDPP_ParaSet.R before running any codes in this pipeline and then source it.
  
  2. Coding Scheme for ABCD Demographic variable data could be found in Step 1 and Step 2, as well as ABCD-DAIRC github repository:[analysis-NDA](https://github.com/ABCD-STUDY/analysis-nda). A coding scheme table was also provided by this pipeline.
  
## Abbreviation Table

Converted from ./.github/SDPP_AbbrTable.xlsx by [Table Convert Online](https://tableconvert.com/)

| Common |                                                | Novel Technology  |                                                                             |
|--------|------------------------------------------------|-------------------|-----------------------------------------------------------------------------|
| T0     | Baseline wave                                  | OS                | OwnerShip                                                                   |
| T1     | One-year follow-up wave                        | STQ               | Screen Time Questionnaire                                                   |
| T2     | Two-year follow-up wave                        | TPD               | TyPical Day (prefix) or Time Per Day (postfix)                              |
| T3     | Three-year follow-up wave                      | TPW               | Time Per Week                                                               |
| T4     | Four-year follow-up wave                       | open              | calculated value from open-answered STQ items                               |
| MVA    | Missing Value Analysis                         | weekday           | in a typical weekday                                                        |
| MI     | Multiple Imputation                            | weekend           | in a typical weekend day                                                    |
| Rep    | auto-generated Report                          | School            | School-related work                                                         |
| Reorg  | Re-organized data                              | SMQ               | Social Media Questionnaire                                                  |
| Rec    | Re-coded data                                  | SOC               | SOCial media apps                                                           |
| Raw    | Raw data                                       | SMAS              | bergen Social Media Addiction Scale                                         |
| Imp    | Imputed data                                   | MVOC              | Multiplayer Videogame Online Chatting                                       |
| Comp   | Compare                                        | UM                | Use Most                                                                    |
| ALL    | all avaiable waves in ABCD 5.0                 | NOFE              | the Number Of FollowErs                                                     |
| S      | Summary (when as postfix of files)             | NOFI              | the Number Of FollowIngs                                                    |
| Sum    | Sum Scores (when as postfix of variable names) | NOA               | the Number Of Account                                                       |
| SMA    | Screen Media Activity                          | MP                | Mobile Phone                                                                |
| MH     | Mental Health                                  | MPIQ              | Mobile Phone Involvement Questionnaire                                      |
|        |                                                | VGAS              | Video Game Addiction Scale                                                  |
|        |                                                | ODQ               | Online Dating Questionnaire                                                 |
|        |                                                | SUAB              | Screen Usage Around Bedtime                                                 |
|        |                                                | Mental Health     |                                                                             |
|        |                                                | BIS               | Behavioral Inhibition System (subscale in BIS/BAS)                          |
|        |                                                | BAS               | Behavioral Activation System (Subscale in BIS/BAS)                          |
|        |                                                | BAS_FS            | BAS Subscale-Fun Seeking (Sum Score)                                        |
|        |                                                | BAS_Drive         | BAS Subscale-Drive (Sum Score)                                              |
|        |                                                | BAS_RR            | BAS Subscale-Reward Responsiveness (Sum Score)                              |
|        |                                                | PEQ               | Peer Experiences Questionnaire                                              |
|        |                                                | Overt             | PEQ Subscale - Overt Aggression or Victimization                            |
|        |                                                | Rel               | PEQ Subscale - Relational Aggression or Victimization                       |
|        |                                                | Rep               | PEQ Subscale - Reputational Aggression or Victimization                     |
|        |                                                | Agg               | PEQ Subscale - Dimension - Aggression                                       |
|        |                                                | Vic               | PEQ Subscale - Dimension - Victimization                                    |
|        |                                                | PPS               | Prodromal Psychosis Scale                                                   |
|        |                                                | PPS_Sum           | PPS Derivatives - Total number of youth-reported psychotic-like experiences |
|        |                                                | PPS_Severity      | PPS Derivatives - The severity score of PPS                                 |
|        |                                                | PPS_Severity_Mean | PPS Derivatives - The mean severity score of PPS                            |
|        |                                                | Mania             | 7-Up Mania Inventory                                                        |
|        |                                                | UPPS              | UPPS-P Children Short Form (ABCD-version)                                   |
|        |                                                | UPPS_LPers        | UPPS-P Subscale - Lack of Perseverance(Sum Score)                           |
|        |                                                | UPPS_LPlan        | UPPS-P Subscale - Lack of Planning (Sum Score)                              |
|        |                                                | UPPS_NU           | UPPS-P Subscale - Negative Urgency (Sum Score)                              |
|        |                                                | UPPS_PU           | UPPS-P Subscale - Positive Urgency (Sum Score)                              |
|        |                                                | UPPS_SS           | UPPS-P Subscale - Sensation Seeking (Sum Score)                             |
|        |                                                | YLE               | Youth-reported Life Events                                                  |
|        |                                                | YLE_Good          | YLE Derivatives - Total number of good events                               |
|        |                                                | YLE_Bad           | YLE Derivatives - Total number of bad events                                |
|        |                                                | YLE_Good_Affected | YLE Derivatives - Mean affected scores of good events                       |
|        |                                                | YLE_Bad_Affected  | YLE Derivatives - Mean affected scores of bad events                        |
|        |                                                | ERQ               | Emotion Regulation Questionnaire                                            |
|        |                                                | ERQ_Reappraisal   | ERQ Subscale - emotion regulation strategies: reapprasial (Sum Score)       |
|        |                                                | ERQ_Suppression   | ERQ Subscale - emotion regulation strategies: Suppression (Sum Score)       |


## Coding Scheme Table

| Variable Names          | Descriptions                                                                                            | Variable Type             | Categories or Data Type                                                                                                                                                                                                                                   | Demographic Imputation Details         |
|-------------------------|---------------------------------------------------------------------------------------------------------|---------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------|
| SexAssigned             | Youth's Sex assigned at birth                                                                           | Categorical (2 Levels)    | Female; Male;                                                                                                                                                                                                                                             | Directly Imputed by MI                 |
| VisitType               | Participants'                                                                                           | Categorical (3 Levels)    | On-site; Remote; Hybrid;                                                                                                                                                                                                                                  | Non-imputed                            |
| Education_13L           | Parent-reported Youth's Education Level                                                                 | Categorical (13 Levels)   | KINGDERGARTEN; 1ST; 2ND; 3RD; 4TH; 5TH; 6TH; 7TH; 8TH; 9TH; 10TH; 11TH; 12TH;                                                                                                                                                                             | Non-imputed                            |
| SiteID                  | ABCD Site ID                                                                                            | Character                 | String data that contains the Site ID number                                                                                                                                                                                                              | Non-imputed                            |
| FamilyID                | Participants' Family ID                                                                                 | Character                 | String data                                                                                                                                                                                                                                               | Non-imputed                            |
| GroupID                 | The in-group order ID, indicates the birth sequence in multi-child famliy                               | Character                 | String data                                                                                                                                                                                                                                               | Non-imputed                            |
| SchoolID                | Participants' School ID                                                                                 | Character                 | String data                                                                                                                                                                                                                                               | Non-imputed                            |
| DistrictID              | The District ID for Participants' School                                                                | Character                 | String data                                                                                                                                                                                                                                               | Non-imputed                            |
| ACS_Weight              | Youth's imputed raked propensity weight                                                                 | Numeric                   | Numeric data in double                                                                                                                                                                                                                                    | Non-imputed                            |
| Race_6L                 | Parent-identified Youth's Race                                                                          | Categorical (6 Levels)    | White; Black; Asian; AIAN; NHPI; Mixed/Other                                                                                                                                                                                                              | Re-coded based on the imputed variable |
| Ethnicity_PrntRep       | Parent-identified Youth's Ethnicity                                                                     | Categorical (2 Levels)    | Hispanic; Non-hispanic                                                                                                                                                                                                                                    | Directly Imputed by MI                 |
| Handedness              | Youth's Handedness (assessed by EHIS)                                                                   | Categorical (3 Levels)    | Right; Left; Mixed;                                                                                                                                                                                                                                       | Non-imputed                            |
| ParentsMarital_2L       | Parent-reported their Marital Status                                                                    | Categorical (2 Levels)    | Married or living with partner; Single;                                                                                                                                                                                                                   | Re-coded based on the imputed variable |
| ParentsHighEdu_2L       | Parent-reported theirselves's Highest Education Level                                                   | Categorical (2 Levels)    | High school or less; College education;                                                                                                                                                                                                                   | Re-coded based on the imputed variable |
| ParentsMarital_X_Employ | the Interaction Term of Parent-reported Marital and Employment Status                                   | Categorical (5 Levels)    | married 0/1/2 in LF; other 0/1 in LF;                                                                                                                                                                                                                     | Re-coded based on the imputed variable |
| Relationship_3L         | Parent-reported Family Structure (Relationship about children)                                          | Categorical (3 Levels)    | Single; Sibling; Twin/Triplet;                                                                                                                                                                                                                            | Directly Imputed by MI                 |
| AdoptionChild           | Parent-reported whether their children are adopted                                                      | Categorical (2 Levels)    | No; Yes;                                                                                                                                                                                                                                                  | Non-imputed                            |
| GenderIdentity_PrntRep  | Parent-reported Youth's Gender Identity                                                                 | Categorical (6 Levels)    | Female; Male; Trans female; Trans male; Gender queer; Different;                                                                                                                                                                                          | Non-imputed                            |
| RaceEthnicity           | The RaceEthnicity Variable from acspsw03 ABCD Data File                                                 | Categorical (5 Levels)    | White; Black; Asian; Hispanic; Other;                                                                                                                                                                                                                     | Non-imputed                            |
| Relationship            | Parent-reported Family Structure (Relationship about children)                                          | Categorical (4 Levels)    | Single; Sibling; Twin; Triplet;                                                                                                                                                                                                                           | Non-imputed                            |
| Religon_PrntRep         | Parent-reported Youth's religon belief                                                                  | Categorical (17 Levels)   | Nothing in Particular; Atheist; Agnostic; Buddhis; Evangelical Protestant; Hindu; Historically Black Church; Jehovahs Witness; Jewish; Mainline Protestant; Mormon; Muslim; Orthodos Christian; Other Christian; Roman Catholic; Unitarian; Someing else; | Non-imputed                            |
| YouthAge_Prnt           | Parent-reported Youth's Age in years                                                                    | Numeric                   | Numeric data in integer                                                                                                                                                                                                                                   | Non-imputed                            |
| AdoptionAge             | Parent-reported the age of youth when they were adopted                                                 | Numeric                   | Numeric data in double                                                                                                                                                                                                                                    | Non-imputed                            |
| USALiveYears            | Parent-reported the Years of their children lived in the USA                                            | Numeric                   | Numeric data in double                                                                                                                                                                                                                                    | Non-imputed                            |
| ParentAge               | Parent Self-reported Age in years                                                                       | Numeric                   | Numeric data in double                                                                                                                                                                                                                                    | Non-imputed                            |
| GenderIdentity_PrntSelf | Parent Self-reported Gender Identity                                                                    | Categorical (6 Levels)    | Female; Male; Trans female; Trans male; Gender queer; Different;                                                                                                                                                                                          | Non-imputed                            |
| Race_PrntSelf           | Parent Self-identified Race                                                                             | Categorical (7 Levels)    | White; Black; Asian; AIAN; NHPI; Mixed; Other                                                                                                                                                                                                             | Non-imputed                            |
| ParentHighEdu           | Parent Self-reported him/her Education Level                                                            | Categorical (5 Levels)    | < HS Diploma; HS Diploma/GED; Some College; Bachelor; Post Graduate Degree;                                                                                                                                                                               | Non-imputed                            |
| PartnerHighEdu          | Parent-reported him/her Partner's Education Level                                                       | Categorical (5 Levels)    | < HS Diploma; HS Diploma/GED; Some College; Bachelor; Post Graduate Degree;                                                                                                                                                                               | Non-imputed                            |
| PartnerEmploy           | Parent-reported him/her Partner's Employment Status                                                     | Categorical (2 Levels)    | Working; Non-working;                                                                                                                                                                                                                                     | Non-imputed                            |
| FamilyNumInLF           | The number of parents in Labor Force in Family                                                          | Numeric                   | Numeric data in integer [0, 1, 2]                                                                                                                                                                                                                         | Non-imputed                            |
| SameSexTwin             | Flag indicates whether a twin pair is same sex twin                                                     | Categorical (2 Levels)    | No; Yes;                                                                                                                                                                                                                                                  | Non-imputed                            |
| GI_PairedSubID_Sub_1    | Genetic Information: genetically related with paticipant-subject ID                                     | Character                 | String data that contains the standard NDA src_subject_id, by descend between participants (postfix 1, 2, 3, 4)                                                                                                                                           | Non-imputed                            |
| GI_PairProb_Sub_1       | Genetic Information: Probability of identity by descend between participant                             | Numeric                   | Numeric data in double, genetic_pi_hat for subject postfix 1 (2, 3, 4)                                                                                                                                                                                    | Non-imputed                            |
| GI_Zygosity_Sub_1       | Genetic Information: Genetically inferred zygosity status between participant and subject ID 1, 2, 3, 4 | Categorical (3 Levels)    | Monozygotic; Dizygotic; Sibling;                                                                                                                                                                                                                          | Non-imputed                            |
| GI_PairedSubID_Sub_2    | Genetic Information: (Same with above)                                                                  | Character                 | String data that contains the standard NDA src_subject_id 2                                                                                                                                                                                               | Non-imputed                            |
| GI_PairProb_Sub_2       | Genetic Information: (Same with above)                                                                  | Numeric                   | Numeric data in double, genetic_pi_hat for subject postfix 2                                                                                                                                                                                              | Non-imputed                            |
| GI_Zygosity_Sub_2       | Genetic Information: (Same with above)                                                                  | Categorical (3 Levels)    | Monozygotic; Dizygotic; Sibling;                                                                                                                                                                                                                          | Non-imputed                            |
| GI_PairedSubID_Sub_3    | Genetic Information: (Same with above)                                                                  | Character                 | String data that contains the standard NDA src_subject_id 3                                                                                                                                                                                               | Non-imputed                            |
| GI_PairProb_Sub_3       | Genetic Information: (Same with above)                                                                  | Numeric                   | Numeric data in double, genetic_pi_hat for subject postfix 3                                                                                                                                                                                              | Non-imputed                            |
| GI_Zygosity_Sub_3       | Genetic Information: (Same with above)                                                                  | Categorical (3 Levels)    | Monozygotic; Dizygotic; Sibling;                                                                                                                                                                                                                          | Non-imputed                            |
| GI_PairedSubID_Sub_4    | Genetic Information: (Same with above)                                                                  | Character                 | String data that contains the standard NDA src_subject_id 4                                                                                                                                                                                               | Non-imputed                            |
| GI_PairProb_Sub_4       | Genetic Information: (Same with above)                                                                  | Numeric                   | Numeric data in double, genetic_pi_hat for subject postfix 4                                                                                                                                                                                              | Non-imputed                            |
| GI_Zygosity_Sub_4       | Genetic Information: (Same with above)                                                                  | Categorical (3 Levels)    | Monozygotic; Dizygotic; Sibling;                                                                                                                                                                                                                          | Non-imputed                            |
| GI_AncestryPC_1         | Genetic Information: First principal component of genetic ancestry                                      | Numeric                   | Numeric data in double, genetic_pc_1                                                                                                                                                                                                                      | Non-imputed                            |
| GI_AncestryPC_2         | Genetic Information: Second principal component of genetic ancestry                                     | Numeric                   | Numeric data in double, genetic_pc_2                                                                                                                                                                                                                      | Non-imputed                            |
| GI_AncestryPC_3         | Genetic Information: Third principal component of genetic ancestry                                      | Numeric                   | Numeric data in double, genetic_pc_3                                                                                                                                                                                                                      | Non-imputed                            |
| GI_AncestryPC_4         | Genetic Information: Fourth principal component of genetic ancestry                                     | Numeric                   | Numeric data in double, genetic_pc_4                                                                                                                                                                                                                      | Non-imputed                            |
| GI_AncestryPC_5         | Genetic Information: Fifth principal component of genetic ancestry                                      | Numeric                   | Numeric data in double, genetic_pc_5                                                                                                                                                                                                                      | Non-imputed                            |
| BirthID                 | Birth event ID determined by rel_family_id and unique birthdates within rel_family_id groups            | Character                 | String data whose last number indicate the birth sequence in the same family (e.g. 1, 2, 3, 4)                                                                                                                                                            | Non-imputed                            |
| Education_R             | Parent-reported Youth's Education Level                                                                 | Ordered Categorical (1-9) | 2ND or  less; 3RD; 4TH; 5TH; 6TH; 7TH; 8TH; 9TH; 10TH or more;                                                                                                                                                                                            | Non-imputed                            |
| Race_4L                 | Parent-identified Youth's Race                                                                          | Categorical (4 Levels)    | White; Black; Asian; Mixed/Other;                                                                                                                                                                                                                         | Re-coded based on the imputed variable |
| Religon_8L              | Parent-reported Youth's religon belief                                                                  | Categorical (8 Levels)    | Nothing in Particular; Atheist; Agnostic; Eastern Asian; Christianity; Jewish;  Muslim; Someing else;                                                                                                                                                     | Non-imputed                            |
| FamilyIncome            | Parent-reported TOTAL COMBINED FAMILY INCOME for the past 12 months                                     | Ordered Categorical       | 1, 2, 3, 4, 5, 6                                                                                                                                                                                                                                          | Directly Imputed by MI                 |
| YouthNativeLang         | Parent-reported Youth's Nativa Language                                                                 | Categorical (2 Levels)    | English; Other;                                                                                                                                                                                                                                           | Directly Imputed by MI                 |
| Religon_2L              | Parent-reported Youth's religon belief                                                                  | Categorical (2 Levels)    | Yes; No;                                                                                                                                                                                                                                                  | Directly Imputed by MI                 |
| HouseholdSize           | Parent-reported the number of family member in household                                                | Ordered Categorical (1-5) | 3 and below; 4; 5; 6; 7 and more;                                                                                                                                                                                                                         | Directly Imputed by MI                 |
| Race_PrntRep            | Parent-identified Youth's Race                                                                          | Categorical (7 Levels)    | White; Black; Asian; AIAN; NHPI; Mixed; Other                                                                                                                                                                                                             | Directly Imputed by MI                 |
| ParentsMarital_6L       | Parent-reported their Marital Status                                                                    | Categorical (6 Levels)    | Married; Living with partner; Divorced; Separated; Widowed; Never married;                                                                                                                                                                                | Directly Imputed by MI                 |
| BMI                     | Youth's Body Mass Index                                                                                 | Numeric                   | Numeric data in double, weight/(height)^2 * 703, weight in lb, height in inch. BMI values above 36 or below 11 were considered as abnormal values and replaced with NAs.                                                                                  | Directly Imputed by MI                 |
| HouseholdStructure      | Parent-reported household structure                                                                     | Categorical               | Single household; Non-single household;                                                                                                                                                                                                                   | Directly Imputed by MI                 |
| ParentEmploy            | Parent Self-reported him/her Employment Status                                                          | Categorical (2 Levels)    | Working; Non-working;                                                                                                                                                                                                                                     | Directly Imputed by MI                 |
| BirthCountry            | Parent-reported the country at birth for their children                                                 | Categorical (2 Levels)    | Other; USA                                                                                                                                                                                                                                                | Non-imputed                            |
| ParentsHighEdu_5L       | Parent-reported theirselves's Highest Education Level                                                   | Categorical (5 Levels)    | < HS Diploma; HS Diploma/GED; Some College; Bachelor; Post Graduate Degree;                                                                                                                                                                               | Directly Imputed by MI                 |



# Data Usage Notes

## Missing Value Analysis Report
  
  The auto-generated Missing Value Analysis (MVA) Reports by this pipeline will be saved into _Res_Preproc_ folder under your project directory (A user-defined parameter in _*SDPP_ParaSet.R*_).
  
  File naming format for MVA report reads as follows:
  
  MVA_*Type*_*AssessmentWave*_*VariableName*_*VariableWave*_*Postfix*_.doc
  
  *Type*: Report-Variable Missing Summary; CaseReport-Case Missing Summary;
  
  *AssessmentWave*: ALL-all avaiable waves in ABCD data; T0; T1; T2; T3; T4;
  
  *VariableName*: abbr in above table, please refer to _domain_ abbrs (e.g. Novel Technology);
  
  *Postfix*: abbr in above table, please refer to _common_ abbrs;


## Missing Value Imputation

  1. In Step 3, missing values (NAs) in some key demographic variable will be processed by R package mice, which reads as follows: _src_subject_id_, _interview_age_, _SexAssigned_, _BMI_, _BirthCountry_, _YouthNativeLang_, _Religon_2L_, _Race_PrntRep_, _Ethnicity_PrntRep_, _ParentsHighEdu_5L_, _ParentsMarital_6L_, _ParentEmploy_, _FamilyIncome_, _HouseholdStructure_, _HouseholdSize_, _Relationship_3L_. Variables with missing values would be imputed using chained equations model. The final imputed dataset will be generated by combining all imputed dataset. The number of imputed datasets could be changed in SDPP_ParaSet (default is 100 with 25 iterations). At the same time, a mice.mids object will also be saved into a RDS file in your SDPP project folder (at /"Project"/Res_2_Results/Res_Preproc/, "Project" is the folder name that you set as a SDPP Project Directory). A more practical way to use multiple-imputed data is calling funcitons in mice package (i.e. with and pool) to build your statistical models on each imputed dataset and then poolling their estimates together. This is a more conventional method when using multiple imputation to handle missing values. In addition, you can change these 'Key Demographic Variables' processed by multiple imputation in **DataPreproc_Step3_DemographicImpute.R** (Code Chunk 6, Line 122 - 130)
  
  2. In Step 5, missing values (NAs) in youth-reported screen use time, MPIQ, SMAS, VGAS, SUAB will be processed by KNN imputation, which is implemented by a MATLAB offical function _knnimpute_ (requires MATLAB offical toolbox: _Bioinformatics Toolbox_). In detail, the Step 5 script will use R.matlab package to create a local MATLAB server and then call the MATLAB function in R environment. Please make sure you have correctly installed the required R package and relevant MATLAB version.

# Data Coding Notes
  
## Demographic Variables
  
  1. Coding scheme for ABCD demographic variable are referred to the ABCD-DAIRC codes. [Find here](https://github.com/ABCD-STUDY/analysis-nda).
  2. A detailed coding scheme table cound be found in /.github/SDPP_CodingScheme.xlsx, which follows the format of **Table S2** in the supplemental materials of our published JAACAP article.[Article Link](https://www.sciencedirect.com/science/article/pii/S0890856723001326)

## ABCD Screen Time Questionnaire

### Changes in ABCD 5.0

  1. In Step 4, some coding details should be noted as follows (Bagot et al., 2022, Dev Cog Neurosci):
  
  - 1.1 Item Choice Changed
    - Beginning in Year 2, the activities listed were changed slightly to reflect the increase in video streaming: watching TV shows or movies changed to “watching or streaming TV shows or movies”; watching videos (such as YouTube) changed to “watching or streaming videos or live streaming (such as YouTube, Twitch)"
  - 1.2 New Items Added
    - Time spent playing videogames was broken down into “time spent on single player”and “multiplayer gaming”. 
    - Editing photos or videos to post on social media was added;
    - “searching or browsing the internet that is not "for school” was added.
    - Total time spent on all non-school related screen usage activities was added.
    - Importantly, the response format in Year 2 was changed from categories to open format, where individuals input the hours and minutes, they estimated spending on each screen usage activity. 
  - 1.3 Coding Method Changed 
    - Bagot et al. have reported their harmonizing method to capture such changes beginning in two-year follow-up wave (Page 5, Section 2.2.10 Self-reported screen usage). SDPP-ABCD-TabDat, here, followed the work done by Bagot et al.
    
        >   "To harmonize screen usage data across Baseline, Year 1, and Year 2 for analyses here, it was necessary to transform Year 2 open responses to categories consistent with Baseline and Year 1. This was done by summing hours and minutes for each activity in Year 2 and recoding it to the categories (with anything above 4 h recoded as ‘4 + hours’), according to a 6-point scale: 0 h, < 1 h, 1–2 h, 2–3 h, 3–4 h, and > 4 h. For analyses, these were coded as 0–5, respectively. Furthermore, ‘editing photos and videos’ and ‘searching or browsing the internet’ were omitted as these items were not queried at previous assessments. Time spent on single player and multiplayer gaming was collapsed into a single category of “video games” (by summing them) to be consistent with previous assessments.".
      
    - In SDPP-ABCD-TabDat, however, Step 4 will do a slightly different coding for screen use time, where a 7-level ordinal coding will be applied to 12 items in the ABCD STQ. This was done by the following formula: Screen Use Time = hours + minutes/60. The calculated time from open-answered items will be re-coding into 0, 0.25, 0.5, 1, 2, 3, 4. The unit is hours. Such re-coding could preserve the raw scale of time from these items, which is beneficial to do clustering analysis. According to the description in previous close-answered items in STQ, which reads as "1½ hours would be coded as 1 hour, rather than 2 hours", Step 4 will collapse 0.75, 1, 1.25 and 1.5 into 1 hour; 1.75, 2, 2.25, 2.5 into 2 hours; 2.75, 3, 3.25, 3.5 into 3 hours; 3.75, 4 and above into 4+ hours.
    
    
    >    _Bagot KS, Tomko RL, Marshall AT, Hermann J, Cummins K, Ksinan A, Kakalis M, Breslin F, Lisdahl KM, Mason M, Redhead JN, Squeglia LM, Thompson WK, Wade T, Tapert SF, Fuemmeler BF, Baker FC. Youth screen use in the ABCD® study. Dev Cogn Neurosci. 2022 Sep 1;57:101150. doi: 10.1016/j.dcn.2022.101150. Epub ahead of print. PMID: 36084446; PMCID: PMC9465320._

### MPIQ

  - Mobile Phone-related Items in the ABCD STQ
    
    -  Mobile phone involvement questionnaire (MPIQ). MPIQ is an 8-item questionnaire designed to assess problematic mobile phone usage, beginning in Year 2. Reference article could be found at:
        
    >     Needing to connect: The effect of self and others on young people's involvement with their mobile phones (2010).
        
    -  MPIQ Item Descriptions: How much do you agree with the following statements in relation to your cell phone use?
    -  Coding: 1=Strongly Disagree; 2=Disagree; 3=Somewhat Disagree; 4=Neither Agree nor Disagree;5=Somewhat Agree; 6=Agree; 7=Strongly Agree; 777=Refuse to Answer.MPIQ Items Descriptions (Q1-Q8): 
    -  screentime_phone1: I interrupt whatever else I am doing when I am contacted on my phone;
    -  screentime_phone2: I often use my phone for no particular reason; 
    -  screentime_phone3: I feel connected to others when I am using my phone; 
    -  screentime_phone4: Arguments have arisen with others because of my phone use; 
    -  screentime_phone5: I lose track of how much I am using my phone; 
    -  screentime_phone6: I often think about my phone when I am not using it; 
    -  screentime_phone7: I have been unable to reduce my phone use; 
    -  screentime_phone8: The thought of being without my phone makes me feel distressed

### SMAS and VGAS

  - 2.5 SMAS and VGAS
    -  Social Media Addiation Scale (SMAS, 6 Items) 
        -  Coding: 1=Never; 2=Very rarely; 3=Rarely; 4=Sometimes; 5=Often; 6=Very often; 777=Refuse to answer
        -  screentime_smqa1: I spend a lot of time thinking about social media apps or planning my use of social media apps;
        -  screentime_smqa2: I feel the need to use social media apps more and more; 
        -  screentime_smqa3: I use social media apps so I can forget about my problems; 
        -  screentime_smqa4: I've tried to use my social media apps less but I can't; 
        -  screentime_smqa5: I've become stressed or upset if I am not allowed to use my social media apps; 
        -  screentime_smqa6: I use social media apps so much that it has had a bad effect on my schoolwork or job; 
    -  Video Game Addiction Scale (VGAS)
        - Items are same with SMAS but replace the "social media" with "playing video games".
        - screentime_vgaq1 ~ screentime_vgaq6	

### SUAB

  - Screen Usage Around Bedtime (SUAB)
    -  A 9-item measure was administered to youth to assess engagement in activities, including screen time activities, prior to sleeping. Items were modified from Lemola et al. (2015) and Arora et al. (2014). On a 5-point Likert scale ranging from 1 (never) to 5 (every night), youth reported how often (in the past week) they engaged in the following activities while already in bed before going to sleep: watch TV or movies, play video games, play music, talk on the phone or text, spend time online on social media, browse the internet, use a computer/laptop for studying. sq3-sq13 shared the same answer items.
    - Coding: 1=0 nights in the past week; 2=1-2 nights; 3=3-4 nights; 4=5-7 nights; 777=Refused to answer.
        - screentime_sq3: Watch or stream movies, videos, or TV shows
        - screentime_sq4: Play video games
        - screentime_sq5: Play music
        - screentime_sq6: Talk on the phone or text (If you do not own a phone, choose 0 nights)
        - screentime_sq7: Spend time online on social media (e.g. Facebook)
        - screentime_sq8: Spend time in chat rooms
        - screentime_sq9: Browse the Internet, Google-ing (not school related)
        - screentime_sq10: Use a computer/laptop for studying
        - screentime_sq11: Reading
    - Four additional items were asked related to sleep and media use which were adapted from questions in a National Sleep Foundation poll (Gradisar et al., 2013). 
        - screentime_sq1: Is there a TV set or an Internet connected electronic device (computer, iPad, phone) in your bedroom? 1=Yes; 0=No; 777=Refuse to answer	
        - screentime_sq2: What do you usually do with your phone when you are ready to go to sleep? Do you: -1=Not Applicable ; 1=Turn the phone off ; 2=Put the ringer on silent or vibrate ; 3=Leave the ringer on ; 4=Put it outside of the room where I sleep ; 777=Refuse to answer
        - screentime_sq12: In the past week, how often have you had phone calls, text messages or emails that wake you after trying to go to sleep? 1=0 nights in the past week; 2=1-2 nights; 3=3-4 nights; 4=5-7 nights; 777=Refused to answer
        - screentime_sq13: In the past week, when you woke up during the night,  how often have you used your phone or other device to send messages/play games/search or browse the internet/use social media/read or write emails? 1=0 nights in the past week; 2=1-2 nights; 3=3-4 nights; 4=5-7 nights; 777=Refused to answer

## ABCD Youth Mental Health Summary

### Processing about nm and nt

  - To get a compact data frame, Step 6 will auto-read ABCD Data Dictionary in working directory to extract key columns that had been indicated in abcd_mhy02.txt (in ABCD 4.0). The other columns such as raw item response will be dropped.

  - The Number of Missings (nm) and the Number of Total questions (nt) are two important flags to indicate the missing values status in ABCD summary data file. To perform double-check in ABCD summary data, Step 6 will call a subfunction _*Recode.ABCD.NM.NT*_ to check whether there are values that have been flagged out, whose NM is equals to NT. Step 6 will automatedly replace these rows with NAs.
  
### Redundant Columns Filtering

 - Some columns in Youth Mental Health Summary were dropped due to there is no need to include these columns in preprocessed data. Details could be found in Step 6. For example, the raw BIS/BAS scale has been proved that is not appropriate for children. Therefore, there is no need to include the raw BIS/BAS subscales sum scores.

## ASEBA Measures

### Child Behavior Checklist (CBCL)

 - **Step 7 will only retain the CBCL t-scores** from all CBCL-related syndrom scales, DSM5-oriented scales and 2007 scales. This will be helpful to reduce the complex of preprocessed data frame.
    - The ASEBA T scores are particularly useful for viewing profiles and multi-informant bar graphs of scale scores, because the T scores provide a metric that is standardized on the basis of comparable percentiles for the different scales and norm groups. However, for statistical analyses, raw scale scores are often preferable, because they reflect all the variation that actually occurs in scores obtained by the individuals whose data are being analyzed. T scores, by contrast, lump together some raw scale scores, such as the different low scores that are given a T score of 50. On the other hand, if the lack of differentiation among very low scale scores is irrelevant (e.g., when few scale scores in an analysis are very low), then use of T scores has the advantage of taking account of differences in the normative distributions for different scales, individuals of different genders and ages, different kinds of informants, and multicultural norm groups.
    - Because T scores are not truncated for the broad-band Internalizing, Externalizing, and Total Problems scales, the T scores for these scales can be analyzed without loss of differentiation among low scale scores. The Manuals and Multicultural Supplements provide more extensive guidance for statistical analyses of raw scale scores, T scores, and other kinds of standard scores (Achenbach et al., 2004; Achenbach & Rescorla, 2000, 2001, 2003, 2007, 2010, 2014b).
    - So that users need not learn the percentile represented by each T score, the ASEBA computer software and hand-scored profiles display percentiles as well as T scores. However, because T scores that are in the clinical range (T >69; >97th percentile for DSM-oriented and syndrome scales) are above the range of meaningful percentiles in normative samples, they are based on the number of possible scores in a scale that exceed the 97th percentile in the normative sample.
 - The Child Behavior Checklist (CBCL) is a component of the Achenbach System of Empirically Based Assessment (ASEBA). The ASEBA is used to detect behavioural and emotional problems in children and adolescents. The CBCL is completed by parents. The other two components are the Teacher’s Report Form (TRF) (completed by teachers), and the Youth Self-Report (YSR) (completed by the child or adolescent himself or herself).
 - The 2001 revision of the CBCL, the CBCL/6-18 (used with children 6 to 18), is made up of eight syndrome scales:
    - anxious/depressed
    - depressed
    - somatic complaints
    - social problems
    - thought problems
    - attention problems
    - rule-breaking behaviour
    - aggressive behaviour
 - These group into two higher order factors—internalizing and externalizing. The time frame for item responses is the past six months.
 - The 2001 revision also added six DSM-oriented scales consistent with DSM diagnostic categories:
    - affective problems
    - anxiety problems
    - somatic problems
    - ADHD
    - oppositional defiant problems
    - conduct problems
 - In addition to the DSM-oriented scales, the ASEBA forms are scored on empirically based syndromes, Internalizing, Externalizing, and Total Problems scales. Some of the forms are also scored on scales shown by research to be good measures of clinical constructs such as:
    - Obsessive-Compulsive Problems (OCD)
    - Post-traumatic Stress Problems (PTSD)
    - sluggish cognitive tempo (SCT)
 - The CBCL (and the YSR) are also scored on (optional) competence scales for activities, social relations, school and total competence. In 2001, options for multicultural norms were added allowing scale scores to be displayed in relation to different sets of cultural/societal norms. Scales were also added for obsessive compulsive disorder (OCD) and posttraumatic stress disorder (PTSD).
 - The CBCL consists of 113 questions, scored on a three-point Likert scale (0=absent, 1= occurs sometimes, 2=occurs often).